name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            /var/lib/docker
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ./target
          key: ${{runner.os}}-${{hashFiles('Cargo.lock', 'Cargo.toml', 'rust-toolchain')}}
      - name: Download Alpine container
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker pull alpine
      - name: Setup build environment
        run: | docker run \
                 -v "$HOME/.cargo:$HOME/.cargo" \
                 -v "$PWD:/eww" \
                 -v "$PWD/.github/workflows/build.sh:/build.sh" \
                 alpine sh -e /build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: x11
          path: x11/eww
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: wayland
          path: wayland/eww
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: no-x11-wayland
          path: no-x11-wayland/eww
          if-no-files-found: error
