name: build

on:
   push:
      branches: [master]
   pull_request:
      branches: [master]

env:
   CARGO_TERM_COLOR: always
   RUSTFLAGS: -C target-feature=+crt-static -C link-self-contained=yes

jobs:
   build-static:
      runs-on: ubuntu-latest
      steps:
         - name: Install docker musl environment
           run: |
             docker pull alpine
             docker run alpine apk add --no-cache build-base gtk+3.0-dev gtk-layer-shell-dev rustup
         - name: Install rust musl target
           run: |
             docker run rustup-init
             docker run -e "PATH=/bin:/usr/bin:$HOME/.cargo/bin" alpine rustup target add x86_64-unknown-linux-musl
         - uses: actions/checkout@v2
         - uses: Swatinem/rust-cache@v1
         - name: Build x11
           run: docker run -e "PATH=/bin:/usr/bin:$HOME/.cargo/bin" alpine cargo check --no-default-features --features=x11 --target x86_64-unknown-linux-musl
         - name: Build wayland
           run: docker run -e "PATH=/bin:/usr/bin:$HOME/.cargo/bin" alpine cargo check --no-default-features --features=wayland --target x86_64-unknown-linux-musl
         - name: Build no-x11-wayland
           run: docker run -e "PATH=/bin:/usr/bin:$HOME/.cargo/bin" alpine cargo check --no-default-features --features=no-x11-wayland --target x86_64-unknown-linux-musl
