name: build

on:
   push:
      branches: [master]
   pull_request:
      branches: [master]

jobs:
   build-static:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Install docker musl environment
           run: |
             docker pull alpine
             pwd
             docker cp . alpine:/eww
             docker run -v "$PWD/.github/workflows/build.sh:/build.sh" alpine sh /build.sh
