name: build

on:
   push:
      branches: [master]
   pull_request:
      branches: [master]

env:
   CARGO_TERM_COLOR: always
   RUSTFLAGS: --target x86_64-unknown-linux-musl -C target-feature=+crt-static -C link-self-contained=yes

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Install dependencies
           run: sudo apt-get update && sudo apt-get install libgtk-3-dev libgtk-layer-shell-dev musl-tools
         - name: Set up
           uses: actions-rs/toolchain@v1
           with:
              toolchain: nightly
              override: true
              components: rustfmt
              default: true
         - name: Install musl toolchain
           run: rustup target add x86_64-unknown-linux-musl
         - uses: actions/checkout@v2
         - uses: Swatinem/rust-cache@v1
         - name: Build x11
           run: cargo check --no-default-features --features=x11
         - name: Build wayland
           run: cargo check --no-default-features --features=wayland
         - name: Build no-x11-wayland
           run: cargo check --no-default-features --features=no-x11-wayland
