name: build

on:
   push:
      branches: [master]
   pull_request:
      branches: [master]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Install docker musl environment
           run: |
             docker pull alpine
             docker run -v "$PWD:/eww" -v "$PWD/.github/workflows/build.sh:/build.sh" alpine sh /build.sh
         - uses: actions/upload-artifact@v2
           with:
             name: x11
             path: x11/eww
             if-no-files-found: error
           with:
             name: wayland
             path: wayland/eww
             if-no-files-found: error
           with:
             name: no-x11-wayland
             path: no-x11-wayland/eww
             if-no-files-found: error
